# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b5caf1937c73328f7f08019b1e022b38b2d264ea3963399ec7839cc92906bc479f2efa783654a6a229d38eceb3720c97b90be8d662e0ea1c8dff50a4d43f03d

test:
  secret_key_base: 63638a90812f65e7187d00f6d852ca81a678a3d6132487ca47d5ddd51ff75220f7c1e3aac49d6c16799861559ff8bdba69b99a65b3b55a80863307c9c95734b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
